task: detection

num_classes: 5
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data1/zy/dataset/cooper001/newsplit/coco/train2017/
    # img_folder: /data1/zy/datasets/zinc/train2017/
    ann_file: /data1/zy/dataset/cooper001/newsplit/coco/annotations/instances_train2017.json
    # ann_file: /data1/zy/datasets/zinc/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data1/zy/dataset/cooper001/newsplit/coco/val2017/
    # img_folder: /data1/zy/datasets/zinc/val2017/
    # ann_file: /data1/zy/datasets/zinc/annotations/val.json
    ann_file: /data1/zy/dataset/cooper001/newsplit/coco/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False
