__include__: [
  # '../dataset/coco_detection.yml',
  '../dataset/custom_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

# output_dir: ./output/rtdetr_r50vd_6x_coco
output_dir: ./output/rtdetr_r50vd_6x_coco_copper_24e_1

epoches: 24
# epoches: 72

num_classes: 5
remap_mscoco_category: False


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data1/zy/dataset/cooper001/newsplit/coco/train2017/
    # img_folder: /data1/zy/datasets/zinc/train2017/
    ann_file: /data1/zy/dataset/cooper001/newsplit/coco/annotations/instances_train2017.json
    # ann_file: /data1/zy/datasets/zinc/annotations/train.json


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data1/zy/dataset/cooper001/newsplit/coco/val2017/
    # img_folder: /data1/zy/datasets/zinc/val2017/
    # ann_file: /data1/zy/datasets/zinc/annotations/val.json
    ann_file: /data1/zy/dataset/cooper001/newsplit/coco/annotations/instances_val2017.json
